<?php

/**
 * @file
 * To allow choose image provider in content generation.
 */

/**
 * Implements hook_menu().
 */
function devel_image_provider_menu() {
  $items['admin/config/development/devel_generate_image_provider'] = array(
    'title' => 'Devel Generate Image Providers',
    'description' => 'Allow choose image provider in content generation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devel_image_provider_providers_form'),
    'access arguments' => array('administer nodes'),
  );
  return $items;
}

/**
 * Admin settings form.
 */
function devel_image_provider_providers_form() {
  $form['devel_generate_image_function'] = array(
    '#type' => 'radios',
    '#title' => t('Choose image provider to use in content generation'),
    '#default_value' => variable_get('devel_generate_image_function', '_image_devel_generate'),
  );

  $form['devel_generate_image_function']['#options'] = module_invoke_all('devel_image_provider');

  return system_settings_form($form);
}

/**
 * Implementats hook_devel_image_provider().
 * For case default
 */
function devel_image_provider_devel_image_provider() {
  $item = array(
    '_image_devel_generate' => t('Default'),
  );
  return $item;
}

/**
 * Return file of $url using selected get_method
 */
function devel_image_provider_get_file($url, $filename, $method = 'curl') {
  $data = NULL;

  switch ($method) {
    case 'curl':
      $data = devel_image_provider_file_get_data_curl($url);
      file_put_contents($filename, $data);
      break;
    case 'gd':
      $image = imagecreatefromjpeg($url);
      imagejpeg($image, $filename);
      imagedestroy($image);
      break;
    case 'file_get_contents':
      $data = file_get_contents($url);
      file_put_contents($filename, $data);
      break;
  }

  return $filename;
}

/**
 * Gets the data from a URL
 * http://davidwalsh.name/download-urls-content-php-curl
 * TODO: FIX PROBLEM sometimes not work for lorempixum provider
 * (get 301 Moved Permanently error message).
 */
function devel_image_provider_file_get_data_curl($url) {
  $ch = curl_init();
  $timeout = 5;
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
  $data = curl_exec($ch);
  curl_close($ch);
  return $data;
}
