<?php

/**
 * @file
 * To use lorempixum.com as image provider in content generation.
 */

/**
 * Implements hook_devel_image_provider().
 */
function lorempixum_image_provider_devel_image_provider() {
  $item = array(
    '_lorempixum_image_provider_generate_image' => 'lorempixum.com'
  );
  return $item;
}

/**
 * Function to generate image
 */
function _lorempixum_image_provider_generate_image($object, $field, $instance, $bundle) {
  static $images = array();

  $min_resolution = empty($instance['settings']['min_resolution']) ? '100x100' : $instance['settings']['min_resolution'];
  $max_resolution = empty($instance['settings']['max_resolution']) ? '600x600' : $instance['settings']['max_resolution'];

  $extension = 'jpg';
  $provider_base_url = 'http://lorempixum.com';

  if (!isset($images[$extension][$min_resolution][$max_resolution]) || count($images[$extension][$min_resolution][$max_resolution]) <= DEVEL_GENERATE_IMAGE_MAX) {
    if ($tmp_file = drupal_tempnam('temporary://', 'imagefield_')) {
      $destination = $tmp_file . '.' . $extension;
      file_unmanaged_move($tmp_file, $destination, FILE_CREATE_DIRECTORY);

      $min = explode('x', $min_resolution);
      $max = explode('x', $max_resolution);

      $width = rand((int) $min[0], (int) $max[0]);
      $height = rand((int) $min[0], (int) $max[0]);

      $gray = variable_get('devel_image_provider_lorempixum_gray', FALSE);
      $gray_part = $gray ? '/g' : '';

      $url = "$provider_base_url" . $gray_part . "/$width/$height";

      $categories = variable_get('devel_image_provider_lorempixum_categories', '');
      $category = array_rand($categories);

      if (!empty($category)) {
        $url .= '/' . $category;
      }

      $method = variable_get('devel_image_provider_lorempixum_get_method', 'file_get_contents');
      $path = devel_image_provider_get_file($url, $destination, $method);

      $source = new stdClass();
      $source->uri = $path;
      $source->uid = 1; // TODO: randomize? Use case specific.
      $source->filemime = 'image/jpg';
      $destination_dir = $field['settings']['uri_scheme'] . '://' . $instance['settings']['file_directory'];
      file_prepare_directory($destination_dir, FILE_CREATE_DIRECTORY);
      $destination = $destination_dir . '/' . basename($path);
      $file = file_move($source, $destination, FILE_CREATE_DIRECTORY);
      $images[$extension][$min_resolution][$max_resolution][$file->fid] = $file;

      $object_field['fid'] = $file->fid;
      $object_field['alt'] = devel_create_greeking(4);
      $object_field['title'] = devel_create_greeking(4);
      return $object_field;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function lorempixum_image_provider_form_devel_image_provider_providers_form_alter(&$form, &$form_state, $form_id) {
  $form['devel_image_provider_lorempixum'] = array(
    '#type' => 'fieldset',
    '#title' => t('Lorempixum settings.'),
    '#states' => array(
      'visible' => array(
        ':input[name="image_devel_generate_function"]' => array('value' => '_lorempixum_image_provider_generate_image'),
      ),
    ),
  );
  //When gd and curl are supported, allow the user to select a method.
  $form['devel_image_provider_lorempixum']['devel_image_provider_lorempixum_get_method'] = array(
    '#type' => 'radios',
    '#title' => t('Method to get files'),
    '#description' => t('Lorempixum plugin will get images using file_get_contents, curl and gd are not functional at the moment.'),
    '#default_value' => variable_get('devel_image_provider_lorempixum_get_method', 'file_get_contents'),
    '#options' => drupal_map_assoc(array('file_get_contents')),
      //'#options' => drupal_map_assoc(array('curl', 'gd', 'file_get_contents')),
  );
  $form['devel_image_provider_lorempixum']['devel_image_provider_lorempixum_gray'] = array(
    '#type' => 'checkbox',
    '#title' => 'Lorempixum Gray',
    '#default_value' => variable_get('devel_image_provider_lorempixum_gray', FALSE),
  );
  $form['devel_image_provider_lorempixum']['devel_image_provider_lorempixum_categories'] = array(
    '#type' => 'select',
    '#title' => 'Lorempixum Categories',
    '#options' => array(
      '' => 'any',
      'abstract' => 'abstract',
      'animals' => 'animals',
      'city' => 'city',
      'food' => 'food',
      'nightlife' => 'nightlife',
      'fashion' => 'fashion',
      'people' => 'people',
      'nature' => 'nature',
      'sports' => 'sports',
      'technics' => 'technics',
      'transport' => 'transport',
    ),
    '#multiple' => TRUE,
    '#size' => 12,
    '#default_value' => variable_get('devel_image_provider_lorempixum_categories', ''),
  );
}
